version: '3'
services:

  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  Astrology:
    image: andressa-raffler/astrology:latest
    build:
      context: .
    container_name: Astrology
    depends_on:
      - db
    ports:
      - '8090:9090'  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  AstrologyFront:
    image: andressa-raffler/astrology-front:latest
    build:
      context: .
      dockerfile: Dockerfile.webapp
    container_name: AstrologyFront
    depends_on:
      - Astrology
    ports:
      - '8081:80'

volumes:
  db:
    driver: local