

CREATE SEQUENCE user_seq INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE person_seq INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE house_seq INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE planet_seq INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE astrology_seq INCREMENT BY 1 START WITH 1;
